name: Auto Update from README

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert README to HTML
        run: |
          # Custom script untuk convert markdown ke HTML
          echo "README updated, rebuild index.html if needed"
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-update from README" || echo "No changes"
          git push
